FORMAT: 1A
HOST: https://peaceful-eyrie-44139.herokuapp.com/

# Todo-Api

This is a simple API for handling todos.


## Todos collection [/todos]

### List all todos [GET]

+ Response 200 (application/json)

    {
        todos:
            [
                {
                    _id: "58a0443b65e83039e8f2241c",
                    text: "Feed the cat!",
                    __v: 0,
                    completedAt: null,
                    completed: false
                }
        ]
    }


### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }