FORMAT: 1A
HOST: https://peaceful-eyrie-44139.herokuapp.com/

# Todo-Api

This is a simple API for handling todos.


## Todos collection [/todos]

### List all todos [GET]

Get a list of all the todos in the collection. Returns a JSON object 
with a todos array containing all of the todos. 

+ Response 200 (application/json)

        {
            todos:
                [
                    {
                        _id: "58a0443b65e83039e8f2241c",
                        text: "Feed the cat!",
                        __v: 0,
                        completedAt: null,
                        completed: false
                    }
                ]
        }


### Create a new todo [POST]

You may create your own todo using this action. It takes a JSON
object containing the text of the todo. 

+ Request (application/json)

        {
            "text": "Feed the cat"
        }

+ Response 201 (application/json)

    + Body

            {
              "__v": 0,
              "text": "Feed the cat",
              "_id": "58a2b368e344cb00114b508f",
              "completedAt": null,
              "completed": false
            }